CMAKE_MINIMUM_REQUIRED(VERSION 3.5...4.0)

PROJECT(smtpping LANGUAGES CXX)
SET(TARGET_NAME "smtpping")

INCLUDE(GNUInstallDirs)

SET(THREADS_PREFER_PTHREAD_FLAG ON)
FIND_PACKAGE(Threads REQUIRED)

ADD_EXECUTABLE(${TARGET_NAME}
	smtpping.cpp
	resolver.cpp
)

TARGET_LINK_LIBRARIES(${TARGET_NAME} PRIVATE Threads::Threads)

IF(APPLE)
	TARGET_COMPILE_DEFINITIONS(${TARGET_NAME} PRIVATE BIND_8_COMPAT)
ENDIF()

IF(CMAKE_SYSTEM_NAME STREQUAL "Linux")
	TARGET_LINK_LIBRARIES(${TARGET_NAME} PRIVATE resolv)
ENDIF()

IF(NOT DEFINED BIN_INSTALL_DIR)
	SET(BIN_INSTALL_DIR "${CMAKE_INSTALL_BINDIR}")
ENDIF()
IF(NOT DEFINED MAN_INSTALL_DIR)
	SET(MAN_INSTALL_DIR "${CMAKE_INSTALL_MANDIR}")
ENDIF()

INSTALL(TARGETS ${TARGET_NAME} RUNTIME DESTINATION ${BIN_INSTALL_DIR})
INSTALL(FILES smtpping.1 DESTINATION ${MAN_INSTALL_DIR}/man1)
